# Generated by Django 4.2.6 on 2023-11-04 12:57

from django.db import migrations, models

import backend.utils
import candidates.models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0002_candidate_image_delete_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="description",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="github_url",
            field=models.URLField(
                blank=True, max_length=150, null=True, verbose_name="github url"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=candidates.models._upload_images,
                validators=[backend.utils.validate_file_extension],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="linkedin_url",
            field=models.URLField(
                blank=True, max_length=150, null=True, verbose_name="linkedin url"
            ),
        ),
    ]
