# Generated by Django 4.2.6 on 2023-12-09 17:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    colorfield.fields.ColorField(
                        default="#5bcaac",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="primary color",
                    ),
                ),
                (
                    "secondary_color",
                    colorfield.fields.ColorField(
                        default="#45a58a",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="secondary color",
                    ),
                ),
                (
                    "font_color",
                    colorfield.fields.ColorField(
                        default="#333333",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="font color",
                    ),
                ),
                (
                    "hover_color",
                    colorfield.fields.ColorField(
                        default="#74e2c4",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="hover color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customization",
                "verbose_name_plural": "Customizations",
            },
        ),
    ]
