# Generated by Django 4.2.6 on 2023-12-23 12:37

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidates", "0003_alter_candidate_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0003_alter_company_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "send_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When both fields are empty message is sent immediately",
                        null=True,
                        verbose_name="send at",
                    ),
                ),
                (
                    "tasks_start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when the messages sending began",
                        null=True,
                        verbose_name="Sending started at",
                    ),
                ),
                (
                    "tasks_finish_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time when all messages have been sent",
                        null=True,
                        verbose_name="Sending finished at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("partial_success", "Partial success"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=15,
                        verbose_name="message status",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="email subject"
                    ),
                ),
                ("content", tinymce.models.HTMLField(verbose_name="message content")),
                ("rq_task_id", models.CharField(blank=True, max_length=36)),
                ("task_info", models.TextField(blank=True, verbose_name="task info")),
                (
                    "candidate",
                    models.ManyToManyField(
                        blank=True,
                        to="candidates.candidate",
                        verbose_name="send to: candidates",
                    ),
                ),
                (
                    "company",
                    models.ManyToManyField(
                        blank=True,
                        to="companies.company",
                        verbose_name="send to: companies",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
