# Generated by Django 4.2.6 on 2023-11-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="title")),
                (
                    "salary_min",
                    models.PositiveIntegerField(verbose_name="minimum salary"),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(verbose_name="maximum salary"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("PLN", "PLN"), ("USD", "USD"), ("EUR", "EUR")],
                        default="PLN",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=4000,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                        ],
                        max_length=6,
                        verbose_name="experience",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("B2B", "B2B"),
                            ("permanent", "Permanent"),
                            ("internship", "Internship"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="employment type",
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=9,
                        null=True,
                        verbose_name="work type",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="tech stack")),
                (
                    "advancement",
                    models.CharField(
                        choices=[
                            ("nice_to_have", "Nice To Have"),
                            ("junior", "Junior"),
                            ("regular", "Regular"),
                            ("advanced", "Advanced"),
                            ("master", "Master"),
                        ],
                        max_length=12,
                        verbose_name="advancement",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_stacks",
                        to="offers.offer",
                        verbose_name="offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tech stack",
                "verbose_name_plural": "Tech stacks",
            },
        ),
    ]
