# Generated by Django 4.2.6 on 2023-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_offer_created_at_offer_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B2B", "B2B"),
                    ("Permanent", "Permanent"),
                    ("Internship", "Internship"),
                ],
                max_length=10,
                null=True,
                verbose_name="employment type",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="experience",
            field=models.CharField(
                choices=[("Junior", "Junior"), ("Mid", "Mid"), ("Senior", "Senior")],
                max_length=6,
                verbose_name="experience",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="work_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Full time", "Full Time"),
                    ("Part time", "Part Time"),
                    ("Freelance", "Freelance"),
                ],
                max_length=9,
                null=True,
                verbose_name="work type",
            ),
        ),
        migrations.AlterField(
            model_name="techstack",
            name="advancement",
            field=models.CharField(
                choices=[
                    ("Nice to have", "Nice To Have"),
                    ("Junior", "Junior"),
                    ("Regular", "Regular"),
                    ("Advanced", "Advanced"),
                    ("Master", "Master"),
                ],
                max_length=12,
                verbose_name="advancement",
            ),
        ),
    ]
