# Generated by Django 4.2.6 on 2023-11-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_alter_candidate_description_and_more"),
        ("offers", "0004_alter_offer_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="candidates",
            field=models.ManyToManyField(
                related_name="offers",
                to="candidates.candidate",
                verbose_name="candidates",
            ),
        ),
    ]
