# Generated by Django 4.2.6 on 2023-11-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_alter_candidate_description_and_more"),
        ("offers", "0005_offer_candidates"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferApplicationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="application date"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_application_histories",
                        to="candidates.candidate",
                        verbose_name="candidate",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_application_history",
                        to="offers.offer",
                        verbose_name="offer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer application history",
                "verbose_name_plural": "Offer application histories",
            },
        ),
    ]
