# Generated by Django 4.2.6 on 2023-11-26 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0006_offerapplicationhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="candidates",
        ),
    ]
