# Generated by Django 4.2.6 on 2024-01-06 15:56

import sort_order_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0007_remove_offer_candidates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": ("-is_promoted", "order"),
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
        migrations.AlterModelOptions(
            name="techstack",
            options={
                "ordering": ("order",),
                "verbose_name": "Tech stack",
                "verbose_name_plural": "Tech stacks",
            },
        ),
        migrations.AddField(
            model_name="offer",
            name="is_promoted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offer",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="techstack",
            name="order",
            field=sort_order_field.fields.SortOrderField(
                db_index=True, default=0, verbose_name="order"
            ),
        ),
    ]
