# Generated by Django 4.2.6 on 2024-01-07 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0008_alter_offer_options_alter_techstack_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={
                "ordering": ("-is_promoted", "order", "-created_at"),
                "verbose_name": "Offer",
                "verbose_name_plural": "Offers",
            },
        ),
    ]
