# Generated by Django 4.2.6 on 2023-11-04 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.utils
import companies.models
import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="name")),
                (
                    "description",
                    models.TextField(max_length=200, verbose_name="description"),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=companies.models._upload_to_company_images,
                        validators=[backend.utils.validate_file_extension],
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
