# Generated by Django 4.2.6 on 2023-11-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="description"
            ),
        ),
    ]
